name: node 
on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v16
      with: 
        python-version: 3.11
    - name: install python package
      run: npm install
    -  run: echo "${{secrets.MY_PASSWORD}}" | sudo -S systemctl restart nginx
    - run: echo "node app.js" > runfile.sh
      shell: bash
   
    - run: pm2 restart all

    
    
      
